services:
  - type: web
    name: orthotrack-app
    runtime: python
    pythonVersion: "3.11"
    buildCommand: pip install -r requirements.txt && pip uninstall -y opencv-python opencv-contrib-python && pip install --force-reinstall --no-deps opencv-python-headless==4.10.0.84
    startCommand: gunicorn app:app
