import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { Link } from 'react-router-dom'
import { supabase } from "../supabaseClient"
import TimelineEventsForm from "../components/TimelineEventsForm"
import TimelineEventEditForm from '../components/TimelineEventEditForm'
import { generateHandoffSummary } from "../lib/geminiClient"
import { jsPDF } from 'jspdf' 


const InjuryDetail = ({ user }) => {
  const { id } = useParams()
  const [injury, setInjury] = useState(null)
  const [events, setEvents] = useState([])
  const [loading, setLoading] = useState(true)
  const [editingEvent, setEditingEvent] = useState(null)
  const [summary, setSummary] = useState(null)
  const [generatingHandoff, setGeneratingHandoff] = useState(false)
  const [showSummaryModal, setShowSummaryModal] = useState(false)

  useEffect(() => {
    fetchInjury()
    fetchEvents()
  }, [id])

  async function fetchInjury() {
    const { data, error } = await supabase
      .from('injuries')
      .select('*')
      .eq('id', id)
      .eq("user_id", user.id)
      .single()

    if (error) {
      console.log("Error:", error.message)
    } else {
      setInjury(data)
    }
    setLoading(false)
  }

  async function fetchEvents() {
    const { data, error } = await supabase
      .from('timeline_events')
      .select('*')
      .eq('injury_id', id)
      .eq("user_id", user.id)
      .order('event_date', { ascending: false })

    if (error) {
      console.log("Error:", error.message)
    } else {
      setEvents(data)
    }
  }

  async function deleteEvent(id){
    const { error } = await supabase
        .from("timeline_events")
        .delete()
        .eq("id", id)

        if(error){
            console.log(error)
        }
        else{
            console.log("Deleted")
            setEvents(events.filter(event => event.id !== id))
        }
  }

  async function deleteDocument(eventId, documentUrl) {
  
  const urlParts = documentUrl.split('/documents/')[1]

  const { error: deleteError } = await supabase.storage
    .from('documents')
    .remove([urlParts])

  if (deleteError) {
    console.log("Error deleting file:", deleteError.message)
    return
  }

  const { error: updateError } = await supabase
    .from('timeline_events')
    .update({
      document_url: null,
      document_name: null,
    })
    .eq('id', eventId)

  if (updateError) {
    console.log("Error updating event:", updateError.message)
  } else {
    fetchEvents()  // Refresh the list
  }
  }

  function serializeForSummary() {
    let summary = `INJURY: ${injury.name}\n`
    summary += `Body Part: ${injury.body_part}\n`
    summary += `Date of Injury: ${injury.injury_date}\n`
    summary += `Description: ${injury.description || 'None'}\n\n`
    
    summary += `TIMELINE OF EVENTS:\n`
    events.forEach(event => {
      summary += `- [${event.event_date}] ${event.type.toUpperCase()}: ${event.title}\n`
      if (event.notes) {
        summary += `  Notes: ${event.notes}\n`
      }
    })
    
    return summary
  }

  async function handleGenerateHandoff() {
    setGeneratingHandoff(true)

    try{
      const injuryData = serializeForSummary()
      const systemPrompt = "You are a clinical documentation specialist.  Given a patient's injury recovery timeline, generate a concise 2-3 paragraph handoff summary  suitable for sharing with a new orthopedic provider or physical therapist.  Include: current injury status, key treatment milestones, current functional limitations (if any), major interventions, current status if inferable, and any notable gaps or follow-up considerations. Do not invent facts. Keep it professional and factual."
      const fullPrompt = `${systemPrompt}\n\nPATIENT DATA:\n${injuryData}`
      console.log(fullPrompt) 
      const result = await generateHandoffSummary(fullPrompt)
      setSummary(result)
      setShowSummaryModal(true)
    }
    
    catch(error){
      console.log("Error generating handoff summary: ", error.message)
    }
    setGeneratingHandoff(false)
  }

  function downloadSummaryPDF(summaryText) {
    const doc = new jsPDF()
    
    doc.setFontSize(14)
    doc.text('Orthopedic Recovery Handoff Summary', 20, 20)
    
    doc.setFontSize(10)
    doc.text(`Patient: ${user.email}`, 20, 30)
    doc.text(`Injury: ${injury.name}`, 20, 38)
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 46)
    
    doc.setFontSize(9)
    const pageHeight = doc.internal.pageSize.getHeight()
    const margin = 20
    const maxWidth = 170
    
    const lines = doc.splitTextToSize(summaryText, maxWidth)
    doc.text(lines, margin, 60)
    
    doc.setFontSize(7)
    doc.text('⚠️ Generated by OrthoTrack. Not a medical document.', margin, pageHeight - 10)
    
    doc.save(`${injury.name}-handoff-${new Date().toISOString().split('T')[0]}.pdf`)
  }

  if (loading) return <div className="p-6">Loading...</div>
  if (!injury) return <div className="p-6">Injury not found</div>

  return (
    <div className="max-w-3xl mx-auto px-6 py-8">
      <Link to="/dashboard" className="text-blue-600 hover:underline mb-4 block"> ← Back to Dashboard </Link>

      <div className="bg-white rounded-xl shadow-md p-6 mb-6">
        <h1 className="text-3xl font-bold mb-2">{injury.name}</h1>
        <p className="text-gray-600 mb-1">
          <strong>Date:</strong> {injury.injury_date}
        </p>
        <p className="text-gray-600 mb-1">
          <strong>Body Part:</strong> {injury.body_part}
        </p>
        {injury.description && (
          <p className="text-gray-600">
            <strong>Description:</strong> {injury.description}
          </p>
        )}
      </div>
      {/* this div displays the injury details */}

    <div className="bg-white rounded-xl shadow-md p-6 mb-6">
      <button
        onClick={handleGenerateHandoff}
        disabled={generatingHandoff}
        className="bg-green-600 text-white px-6 py-3 rounded-lg hover:bg-green-700 disabled:bg-gray-400"
      >
        {generatingHandoff ? "Generating..." : "Generate Handoff Summary"}
      </button>
    </div>
    {/* this is for the generatingHandoff button */}

    {showSummaryModal && (
      <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
        <div className="bg-white rounded-xl shadow-xl max-w-2xl w-full p-8 relative">
          <button onClick={() => setShowSummaryModal(false)} className="absolute top-4 right-4 text-gray-500 hover:text-black"> ✕ </button>
          <h3 className="text-lg font-bold mb-3">Clinical Handoff Summary</h3>
          <div className="text-gray-700 whitespace-pre-wrap mb-4">
            {summary}
          </div>
          <p className="text-xs text-gray-500 italic">
            ⚠️ Generated by OrthoTrack. This is a summary of your personal recovery records and is not a medical document or clinical diagnosis.
          </p>
          <button
            onClick={() => downloadSummaryPDF(summary)}
            className="mt-4 bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700"
          >
            Download as PDF
          </button>
        </div>
      </div>
      // this is the summary modal
    )}

      <TimelineEventsForm
      injuryId={id}
      user={user}
      onEventCreated={fetchEvents}
      />

      {editingEvent && (
        <TimelineEventEditForm
          event={editingEvent}
          injuryId={id}
          user={user}
          onEventUpdated={() => {
            setEditingEvent(null)
            fetchEvents()
          }}
          onCancel={() => setEditingEvent(null)}
        />
      )}

      <div>
        <h2 className="text-2xl font-bold mb-4">Timeline</h2>
        {events.length === 0 ? (
          <p className="text-gray-500">No events yet. Add one above!</p>
        ) : (
          events.map((event) => (
            <div
              key={event.id}
              className="bg-white rounded-lg shadow-md p-4 mb-4 border-l-4 border-blue-600"
            >
              <div className="flex justify-between items-start">
                <div className="flex flex-col">
                  <h3 className="font-bold text-lg">{event.title}</h3>
                  <p className="text-sm text-gray-500 mb-2">
                    {event.event_date} • {event.type}
                  </p>
                  {event.notes && (
                    <p className="text-gray-700 mb-2">{event.notes}</p>
                  )}
                  {event.document_url && (
                    <div className="flex items-center gap-2"> 
                      <a
                          href={event.document_url}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-blue-600 hover:underline text-sm"
                      >
                          📄 {event.document_name}
                      </a>
                      <button 
                      onClick={() => deleteDocument(event.id, event.document_url)}
                      className="text-red-600 hover:text-red-800 text-sm font-semibold"
                      > 
                        Remove Document
                        </button>
                    </div>
                )}
                  <button onClick={() => setEditingEvent(event)} className="border border-cyan-700">Edit</button>
                  <button onClick={() => deleteEvent(event.id)} className="border border-cyan-700">Delete</button>
                </div>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  )
}

export default InjuryDetail